# -*- coding: utf-8 -*-
"""weather_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-04-6a050d0640a7/locations/us-central1/repositories/d800189e-5210-4180-8196-296fcf00c218
"""

# Commented out IPython magic to ensure Python compatibility.
# #create dataset
# %%bigquery
# CREATE SCHEMA IF NOT EXISTS weather_dataset
# OPTIONS(
# location="us",
# default_table_expiration_days=14);

# Commented out IPython magic to ensure Python compatibility.
# #create Table
# %%bigquery
# CREATE OR REPLACE EXTERNAL TABLE `qwiklabs-gcp-04-6a050d0640a7.weather_dataset.weather_table`
# OPTIONS (
#   format = 'CSV',
#   uris = ['gs://labs.roitraining.com/data-to-ai-workshop/weather_data.csv'],
#   skip_leading_rows = 1,
#   allow_jagged_rows = false,
#   allow_quoted_newlines = false,
#   field_delimiter = ',',
#   max_bad_records = 10
# )

# Commented out IPython magic to ensure Python compatibility.
# #Connection to gemini model
# %%bigquery
# CREATE OR REPLACE MODEL `qwiklabs-gcp-04-6a050d0640a7.weather_dataset.gemini_model` REMOTE
# WITH CONNECTION DEFAULT OPTIONS (ENDPOINT = 'gemini-2.0-flash');

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery forcast
# CREATE OR REPLACE TABLE
#   `qwiklabs-gcp-04-6a050d0640a7.weather_dataset.forcast` AS (
# SELECT
#   ml_generate_text_result['candidates'][0]['content']["parts"][0]["text"] AS generated_text,
#   *
# FROM
#   ML.GENERATE_TEXT(
#     MODEL `qwiklabs-gcp-04-6a050d0640a7.weather_dataset.gemini_model`,
#     (
#       SELECT
#         CONCAT('Provide a believable weather forecast for the following data: ',
#         date, city, state, temperature_f, wind_speed_mph, precipitation_in, barometric_pressure_inHg, humidity_percent, weather_condition) AS prompt
#       FROM
#         `qwiklabs-gcp-04-6a050d0640a7.weather_dataset.weather_table`
#     ),
#     STRUCT(
#       0.2 AS temperature,
#       1000 AS max_output_tokens)));

forcast
