# -*- coding: utf-8 -*-
"""fraud_training_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-04-6a050d0640a7/locations/us-central1/repositories/c4b354f7-b978-471b-9caf-b5940d9a92fe
"""

# Commented out IPython magic to ensure Python compatibility.
# #create dataset
# %%bigquery
# CREATE SCHEMA IF NOT EXISTS fraud_data
# OPTIONS(
# location="us",
# default_table_expiration_days=14);

# Commented out IPython magic to ensure Python compatibility.
# #create Table
# %%bigquery
# CREATE OR REPLACE EXTERNAL TABLE `qwiklabs-gcp-04-6a050d0640a7.fraud_data.fraud_data_table`
# OPTIONS (
#   format = 'CSV',
#   uris = ['gs://labs.roitraining.com/data-to-ai-workshop/fraud_data_raw.csv'],
#   skip_leading_rows = 1,
#   allow_jagged_rows = false,
#   allow_quoted_newlines = false,
#   field_delimiter = ',',
#   max_bad_records = 10
# )

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE TABLE `qwiklabs-gcp-04-6a050d0640a7.fraud_data.fraud_training_data` AS (
#   SELECT
#     * EXCEPT (
#       Employment_Status, Device_Type, Age, Previous_Assistance_Received, Supporting_Doc_Verified
#     ),
#   -- a. One-hot encode the Employment_Status
#   CASE WHEN Employment_Status = 'Employed' THEN 1 ELSE 0 END AS OHE_Employed,
#   CASE WHEN Employment_Status = 'Unemployed' THEN 1 ELSE 0 END AS OHE_Unemployed,
#   CASE WHEN Employment_Status = 'Self-employed' THEN 1 ELSE 0 END AS OHE_Self_employed,
#   CASE WHEN Device_Type = 'Mobile' THEN 1 ELSE 0 END AS OHE_Device_Mobile,
#   CASE WHEN Device_Type = 'Desktop' THEN 1 ELSE 0 END AS OHE_Device_Desktop,
#   CASE WHEN Device_Type = 'Tablet' THEN 1 ELSE 0 END AS device_type_tablet,
# 
#   -- b. Break the age field into bins
#   CASE
#     WHEN Age BETWEEN 18 AND 24 THEN '18-24'
#     WHEN Age BETWEEN 25 AND 34 THEN '25-34'
#     WHEN Age BETWEEN 35 AND 44 THEN '35-44'
#     WHEN Age BETWEEN 45 AND 54 THEN '45-54'
#     WHEN Age BETWEEN 55 AND 64 THEN '55-64'
#     ELSE '65+'
#   END AS age_bin,
# 
#   -- c. Create a field called Income-to-Amount-Requested
#   SAFE_DIVIDE(Income, Amount_Requested) AS Income_to_Amount_Requested,
# 
#   -- d. Create a calculated field called Time_Since_Previous_Assistance
#   -- This assumes 'name' is a customer identifier and 'ApplicationDate' is the date of the request.
#   DATE_DIFF(CURRENT_DATE(), Previous_Assistance_Date, DAY) AS Time_Since_Previous_Assistance,
# 
#   -- e. Change True/False fields to 0s and 1s
#   CAST(Previous_Assistance_Received AS INT64) AS Previous_Assistance_Received_int,
#   CAST(Supporting_Doc_Verified AS INT64) AS Supporting_Doc_Verified_int
# FROM
#   `qwiklabs-gcp-04-6a050d0640a7.fraud_data.fraud_data_table`
# );